# Generated by Django 5.2.13 on 2026-05-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DOCUMENTS_REQUIRED', 'Documents Required'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PRINTED_PENDING_SIGNATURE', 'Printed, Pending Signature'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DOCUMENTS_REQUIRED', max_length=35)),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(db_index=True, help_text='Digits only, no dashes', max_length=13)),
                ('mobile', models.CharField(max_length=20)),
                ('postal_address', models.TextField()),
                ('registration_no', models.CharField(db_index=True, max_length=100)),
                ('roll_no', models.CharField(blank=True, max_length=100)),
                ('session_year', models.CharField(max_length=50)),
                ('exam_passing_year', models.CharField(blank=True, max_length=20)),
                ('declared_result_date', models.DateField()),
                ('verified_result_date', models.DateField(blank=True, null=True)),
                ('application_type', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], max_length=20)),
                ('fee_timing_at_entry', models.CharField(choices=[('BEFORE_TIME', 'Before Time'), ('AFTER_TIME', 'After Time')], max_length=20)),
                ('required_fee_at_entry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fee_timing', models.CharField(blank=True, choices=[('BEFORE_TIME', 'Before Time'), ('AFTER_TIME', 'After Time')], max_length=20)),
                ('final_required_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_mode', models.CharField(choices=[('SELF', 'Self'), ('REPRESENTATIVE', 'Representative'), ('COURIER', 'Courier')], default='SELF', max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('receiver_cnic', models.CharField(blank=True, max_length=13)),
                ('receiver_mobile', models.CharField(blank=True, max_length=20)),
                ('receiving_remarks', models.CharField(blank=True, max_length=255)),
                ('degree_serial_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('degree_book_no', models.CharField(blank=True, max_length=100)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to_name', models.CharField(blank=True, max_length=255)),
                ('delivered_to_cnic', models.CharField(blank=True, max_length=13)),
                ('delivered_to_mobile', models.CharField(blank=True, max_length=20)),
                ('delivery_mode', models.CharField(blank=True, choices=[('SELF', 'Self'), ('REPRESENTATIVE', 'Representative'), ('COURIER', 'Courier')], max_length=20)),
                ('courier_company', models.CharField(blank=True, max_length=120)),
                ('courier_tracking_no', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_degree_applications', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.institute')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_degrees', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('DOCUMENTS_REQUIRED', 'Documents Required'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PRINTED_PENDING_SIGNATURE', 'Printed, Pending Signature'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=35)),
                ('to_status', models.CharField(choices=[('DOCUMENTS_REQUIRED', 'Documents Required'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PRINTED_PENDING_SIGNATURE', 'Printed, Pending Signature'), ('READY_FOR_COLLECTION', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=35)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='degree.degreeapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_completely_filled', models.BooleanField(default=False)),
                ('form_signed', models.BooleanField(default=False)),
                ('attestations_complete', models.BooleanField(default=False)),
                ('paid_challan_attached', models.BooleanField(default=False)),
                ('original_clearance_attached', models.BooleanField(default=False)),
                ('transcript_dmc_copy_attached', models.BooleanField(default=False)),
                ('cnic_copy_attached', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='degree.degreeapplication')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_level', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('MPHIL', 'MPhil'), ('PHD', 'PhD'), ('DIPLOMA', 'Diploma'), ('OTHER', 'Other')], max_length=20)),
                ('application_type', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], max_length=20)),
                ('timing', models.CharField(choices=[('BEFORE_TIME', 'Before Time'), ('AFTER_TIME', 'After Time')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['program_level', 'application_type', 'timing'],
                'unique_together': {('program_level', 'application_type', 'timing', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='VCFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('RETURNED', 'Returned / Ready for Collection')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vc_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=100)),
                ('challan_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('INITIAL', 'Initial Fee'), ('ADDITIONAL', 'Additional Fee')], default='INITIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.bank')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='degree.degreeapplication')),
            ],
            options={
                'ordering': ['-challan_date'],
                'unique_together': {('bank', 'challan_no')},
            },
        ),
        migrations.CreateModel(
            name='VCFileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vc_file_item', to='degree.degreeapplication')),
                ('vc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='degree.vcfile')),
            ],
            options={
                'ordering': ['serial_no'],
                'unique_together': {('vc_file', 'serial_no')},
            },
        ),
    ]
