# Generated by Django 5.2.13 on 2026-05-05 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['program_level', 'timing', 'application_type', '-effective_from']},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='degreeapplication',
            name='fee_structure_at_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='degree.feestructure'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date from which this fee becomes applicable.'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Automatically filled when a newer fee replaces this one.', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['program_level', 'application_type', 'timing', 'effective_from'], name='degree_fees_program_e3b711_idx'),
        ),
    ]
