# Generated by Django 5.2.13 on 2026-05-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0002_add_application_email'),
        ('degree', '0002_alter_feestructure_options_and_more'),
    ]

    operations = [
    ]
