# Generated by ChatGPT on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0003_merge_20260505_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeapplication',
            name='courier_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
