# Generated by Django 5.2.13 on 2026-05-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_campus_department'),
        ('degree', '0007_status_vc_file_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeapplication',
            name='institute',
        ),
        migrations.AddField(
            model_name='degreeapplication',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.campus'),
        ),
        migrations.AddField(
            model_name='degreeapplication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='vcfile',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('RETURNED', 'Received / Ready for Collection')], default='DRAFT', max_length=20),
        ),
    ]
