# Generated by Django 5.2.13 on 2026-06-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0010_certificate_type_fee_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feestructure',
            new_name='degree_fees_program_b40646_idx',
            old_name='degree_fees_program_cer_idx',
        ),
    ]
