# Generated by Django 5.2.13 on 2026-05-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_campus_department'),
        ('degree', '0008_remove_degreeapplication_institute_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.AddField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.campus'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('campus', 'name')},
        ),
    ]
